apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alexa-bridge
  namespace: alexa-bridge
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - alexa-bridge.phoenixlab.me
    secretName: alexa-bridge-tls
  rules:
  - host: alexa-bridge.phoenixlab.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alexa-bridge
            port:
              number: 8000
